# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Place_ID_Yelp',
            fields=[
                ('restaraunt_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('phone_num', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
                ('image_url', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Place_ID_Zomato',
            fields=[
                ('restaraunt_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('cusine', models.CharField(max_length=256)),
                ('menu_url', models.CharField(max_length=256)),
                ('average_cost_for_two', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_detail_title', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=256)),
                ('ingredients', models.TextField()),
                ('recipe_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Yelp_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('user_image', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('review_text', models.TextField()),
                ('url_link', models.CharField(max_length=256)),
                ('food_place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Food_Place_ID_Yelp')),
            ],
        ),
        migrations.CreateModel(
            name='Zomato_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=256)),
                ('user_image', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('review_text', models.TextField()),
                ('food_place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Food_Place_ID_Zomato')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
