# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180410_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_place_id_zomato',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
