# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_food_place_id_zomato_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='rating',
            new_name='readyInMinutes',
        ),
    ]
