# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180417_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.CharField(max_length=256)),
                ('user_selected_food_place', models.CharField(max_length=256)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User_Detail')),
            ],
        ),
        migrations.AlterField(
            model_name='food_place_id_yelp',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
