# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180417_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_detail',
            name='recipe_detail_id',
        ),
        migrations.RemoveField(
            model_name='yelp_review',
            name='food_place_id',
        ),
        migrations.RemoveField(
            model_name='zomato_review',
            name='food_place_id',
        ),
        migrations.DeleteModel(
            name='Recipe_Detail',
        ),
        migrations.DeleteModel(
            name='Yelp_Review',
        ),
        migrations.DeleteModel(
            name='Zomato_Review',
        ),
    ]
