# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180423_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cusine',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
